'use client';

import { motion, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Github, Linkedin, Mail, Command, ExternalLink } from 'lucide-react';
import { useState } from 'react';

const projects = [
 {n:'01',name:'EMPLO Salary',type:'Employee Salary Prediction',metrics:['100K synthetic records','95% stated prediction accuracy'],desc:'An interactive employee salary intelligence platform that compares machine-learning approaches before selecting a regression model. It also explores compensation factors and supports in-hand salary estimation based on company-specific structures.',stack:'Python · Regression · React',live:'https://emplo-salary.vercel.app/',github:'https://github.com/Uttamchaudhary07/emploSalary'},
 {n:'02',name:'AI Face Recognition',type:'Real-time Computer Vision',metrics:['~97% recognition accuracy','Real-time + liveness detection','No custom training dataset'],desc:'A lightweight real-time face recognition system using face-api.js. Recognition is paired with liveness detection to move beyond simple image matching toward practical identity verification.',stack:'MERN · JavaScript · face-api.js · Computer Vision',live:'https://facerecognition.sagarjaiswal.dev/'},
 {n:'03',name:'SubGen',type:'AI Subtitle Workflow',metrics:['macOS workflow','Low-latency focus'],desc:'An AI-powered subtitle generation system focused on making transcription and subtitle synchronization feel fast and unobtrusive. The project explores the complete pipeline from audio processing to subtitle output.',stack:'Python · AI · Speech Recognition · macOS'},
 {n:'04',name:'Diagnomind',type:'Clinical Reasoning Model',metrics:['MIMIC-IV dataset','Reasoning over prediction'],desc:'A medical reasoning model built around clinical evidence. Instead of treating diagnosis as a black-box prediction task, Diagnomind explores why a diagnosis would be plausible and how evidence can support a reasoning chain.',stack:'Python · Machine Learning · NLP · Clinical Data'}
];
const skillGroups=[['Languages','Python','Java','JavaScript','SQL','HTML','CSS'],['AI / ML','NumPy','Pandas','Scikit-learn','OpenCV','NLP','Computer Vision','RAG','LLMs','AI Agents'],['Full Stack / Backend','React','Node.js','Express.js','MongoDB','Redis','REST APIs'],['System Design & Engineering','System Design','System Architecture','API Design','Database Design','Data Modeling','Caching','Performance Optimization','Scalability','Distributed Systems','OOP','Data Structures & Algorithms','Testing & Debugging'],['Developer Tools','Git','GitHub','Postman','Docker','VS Code','npm']];

export default function Home(){
 const {scrollYProgress}=useScroll(); const rotate=useTransform(scrollYProgress,[0,1],[-18,210]); const arc=useSpring(rotate,{stiffness:50,damping:20}); const [open,setOpen]=useState(false);
 return <main>
  <nav className="fixed top-0 z-50 w-full px-5 md:px-10 py-5 mix-blend-multiply"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="#top" className="mono text-xs tracking-[.22em]">UTTAM / 0.1</a><div className="hidden gap-7 md:flex mono text-[10px] tracking-[.18em]"><a href="#work">WORK</a><a href="#thinking">THINKING</a><a href="#stack">STACK</a><a href="#perso">PERSO</a></div><button onClick={()=>setOpen(true)} className="rounded-full border border-black/20 p-2"><Command size={16}/></button></div></nav>
  {open&&<div className="fixed inset-0 z-[60] grid place-items-center bg-[#291C0E]/80 p-6" onClick={()=>setOpen(false)}><div className="w-full max-w-sm rounded-3xl bg-[#E1D4C2] p-7" onClick={e=>e.stopPropagation()}><div className="mono mb-6 text-[10px] tracking-[.2em]">UTTAM.OS / NAV</div>{['work','thinking','stack','perso','contact'].map(x=><a key={x} onClick={()=>setOpen(false)} href={'#'+x} className="serif block border-t border-black/15 py-4 text-3xl capitalize">{x}<ArrowUpRight className="inline ml-2" size={20}/></a>)}</div></div>}

  <section id="top" className="relative min-h-screen overflow-hidden grid-bg px-5 md:px-10 pt-32 pb-20"><div className="mx-auto max-w-7xl"><div className="grid min-h-[78vh] items-end gap-12 lg:grid-cols-[1.25fr_.75fr]"><div><p className="mono mb-8 text-[10px] tracking-[.28em]">AI & SOFTWARE DEVELOPER · BENGALURU</p><h1 className="serif max-w-5xl text-[clamp(4rem,10vw,9.5rem)] leading-[.82] tracking-[-.05em]">Curious about<br/>technology.<br/><i>Obsessed with building.</i></h1><p className="mt-10 max-w-xl text-base leading-7 md:text-lg">Exploring the boundary between software and intelligence — by building systems that make things easier.</p><div className="mt-10 flex items-center gap-5"><a href="#work" className="inline-flex items-center gap-3 rounded-full bg-[#291C0E] px-6 py-3 text-sm text-[#E1D4C2]">Explore work <ArrowDown size={16}/></a><span className="mono text-[9px] tracking-[.18em]">AI · SOFTWARE · SYSTEMS</span></div></div><div className="relative hidden h-[420px] lg:block"><motion.div style={{rotate:arc}} className="arc absolute -right-32 top-0 h-[520px] w-[520px]"/><motion.div style={{rotate:arc}} className="arc absolute right-2 top-28 h-[300px] w-[300px] border-[#DB9F75]"/><div className="absolute right-20 top-48 mono text-[9px] leading-6">SYSTEM / ONLINE<br/>FOCUS / AI SYSTEMS<br/>MODE / BUILD</div></div></div></div><div className="absolute bottom-8 left-5 mono text-[9px] tracking-[.2em] md:left-10">SCROLL TO EXPLORE</div></section>

  <section id="thinking" className="px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="mb-14 flex items-start justify-between gap-8"><div><p className="mono text-[10px] tracking-[.22em]">01 / WHY I BUILD</p><h2 className="serif mt-5 text-5xl md:text-7xl">Curiosity becomes<br/><i>something real.</i></h2></div><div className="mono hidden text-[9px] leading-5 md:block">CURIOUS → BUILD → BREAK<br/>→ UNDERSTAND → IMPROVE</div></div><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div className="relative min-h-[330px]"><motion.div style={{rotate:arc}} className="arc absolute left-0 top-0 h-[310px] w-[310px]"/><div className="absolute left-24 top-24 mono text-[9px] tracking-[.18em]">MAKE THINGS<br/>EASIER</div></div><div className="max-w-2xl text-2xl leading-9 md:text-[2.05rem] md:leading-[1.28]"><p>I get curious. I build something. I break it. I learn why. Then I build it better.</p><p className="mt-8 text-[#6E473B]">Ultimately, I want to make things easier — predicting something, automating something, understanding something, or simply removing a little friction from someone’s day.</p></div></div></div></section>

  <section id="work" className="bg-[#14252C] px-5 py-20 text-[#E1D4C2] md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="mono text-[10px] tracking-[.22em] text-[#DB9F75]">02 / SELECTED WORK</p><h2 className="serif mt-5 text-6xl md:text-8xl">Built.<br/><i>Tested.</i></h2></div><span className="mono text-[10px]">04 PROJECTS</span></div><div className="mt-14 divide-y divide-[#E1D4C2]/15">{projects.map((p,i)=><motion.article key={p.name} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.6,delay:i*.05}} className="grid gap-7 py-10 lg:grid-cols-[64px_1fr_1.15fr] lg:py-12"><div className="mono text-[10px] text-[#A78D78]">{p.n}</div><div><div className="mono text-[9px] tracking-[.18em] text-[#DB9F75]">{p.type}</div><h3 className="serif mt-3 text-4xl md:text-6xl">{p.name}</h3><div className="mt-5 flex flex-wrap gap-2">{p.metrics.map(m=><span key={m} className="rounded-full border border-[#E1D4C2]/20 px-3 py-1 mono text-[9px]">{m}</span>)}</div></div><div><p className="max-w-xl text-base leading-7 text-[#BEB5A9] md:text-lg md:leading-8">{p.desc}</p><p className="mono mt-6 text-[9px] tracking-[.08em] text-[#A78D78]">{p.stack}</p><div className="mt-7 flex gap-5">{p.live&&<a className="inline-flex items-center gap-2 text-sm" href={p.live} target="_blank" rel="noreferrer">Live <ExternalLink size={14}/></a>}{p.github&&<a className="inline-flex items-center gap-2 text-sm" href={p.github} target="_blank" rel="noreferrer"><Github size={14}/> GitHub</a>}</div></div></motion.article>)}</div></div></section>

  <section id="stack" className="px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><p className="mono text-[10px] tracking-[.22em]">03 / THE STACK</p><h2 className="serif mt-5 max-w-3xl text-5xl leading-none md:text-7xl">Tools I use to turn<br/><i>ideas into systems.</i></h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{skillGroups.map((g,i)=><motion.div key={g[0]} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.45,delay:i*.04}} className="stack-card group rounded-3xl border border-black/12 bg-[#BEB5A9]/35 p-6 md:p-7"><div className="flex items-start justify-between gap-4"><h3 className="mono text-[11px] tracking-[.14em]">{g[0]}</h3><span className="mono text-[10px] text-[#82401D]">{String(g.length-1).padStart(2,'0')}</span></div><div className="mt-6 flex flex-wrap gap-2">{g.slice(1).map(s=><span key={s} className="skill-pill rounded-full border border-black/12 bg-[#E1D4C2]/70 px-3 py-2 text-sm md:text-[15px]">{s}</span>)}</div></motion.div>)}</div></div></section>

  <section id="perso" className="relative overflow-hidden bg-[#BEB5A9] px-5 py-24 md:px-10 md:py-32"><motion.div style={{rotate:arc}} className="arc absolute -right-48 top-10 h-[700px] w-[700px] border-black/15"/><div className="relative mx-auto max-w-7xl"><p className="mono text-[10px] tracking-[.22em]">04 / WHAT I’M BUILDING TOWARD</p><div className="mt-12 max-w-4xl"><div className="mono text-[10px] text-[#82401D]">IN DEVELOPMENT</div><h2 className="serif mt-4 text-[clamp(5rem,14vw,12rem)] leading-[.75] tracking-[-.06em]">PERSO</h2><p className="serif mt-14 max-w-2xl text-3xl leading-tight md:text-5xl">What if your computer didn’t just respond to you, but understood your world?</p><p className="mt-8 max-w-xl text-lg leading-8 text-[#6E473B]">Perso is my exploration into a personal AI operating system — one that can understand context, maintain memory, reason about the user’s world, and eventually act on its own.</p></div><div className="mt-16 grid max-w-2xl grid-cols-2 gap-3 md:grid-cols-4"><span className="rounded-2xl border border-black/15 p-4 mono text-[9px]">MEMORY</span><span className="rounded-2xl border border-black/15 p-4 mono text-[9px]">REASONING</span><span className="rounded-2xl border border-black/15 p-4 mono text-[9px]">CONTEXT</span><span className="rounded-2xl border border-black/15 p-4 mono text-[9px]">ACTION</span></div></div></section>

  <section id="contact" className="bg-[#291C0E] px-5 py-24 text-[#E1D4C2] md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><p className="mono text-[10px] tracking-[.22em] text-[#DB9F75]">05 / CONTACT</p><h2 className="serif mt-8 max-w-4xl text-6xl leading-[.9] md:text-9xl">Let’s build<br/><i>something useful.</i></h2><a href="mailto:uttamchaudhary020@gmail.com" className="mt-12 inline-flex items-center gap-3 border-b border-[#E1D4C2]/40 pb-2 text-lg">uttamchaudhary020@gmail.com <Mail size={17}/></a><div className="mt-28 flex flex-wrap gap-6 border-t border-[#E1D4C2]/15 pt-6"><a href="https://github.com/Uttamchaudhary07" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mono text-[10px]"><Github size={14}/> GitHub</a><a href="https://www.linkedin.com/in/uttamchaudhary07/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mono text-[10px]"><Linkedin size={14}/> LinkedIn</a><span className="ml-auto mono text-[9px] text-[#A78D78]">© {new Date().getFullYear()} UTTAM CHAUDHARY / V0.1</span></div></div></section>
 </main>
}
